### ISSUE TITLE
What to do when there's a rendering problem?

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/MiServer#58]
A couple of ideas to provide the user more information when something breaks during rendering.

1.  When not in production mode (as defined by the setting of /Config/Server.xml:Production), attempt to identify the "user level" element that contains mis-rendering element.  This would involve looking up the rendering hierarchy to try and identify the user element.  The challenge is that many of our widgets build content under the covers...

1. When an element breaks during render, replace the content with something that would be visible on the page to indicate "this didn't render".  This should be controlled by a new configuration setting.

**Comment by mbaas2** [comment]
So #2 would only be valid for production sites, right? I think giving a
production-user the chance to interact with a broken page (by replacing
just the broken control's rendered html with something else) is likely to
create all sorts of problems - instead of trying to be clever there, I
would much prefer some enhanced error-logging - and a 500 Redirect for the
frontend. And that "enhanced logging" is something that will probably be
related to the outcome of #1 anyway... ;-)

2017-01-16 16:46 GMT+01:00 Brian Becker <notifications@github.com>:

**Comment by bpbecker** [comment]
I envision both of these to be useful during website development, and not intended to be active for a "production" site.  Setting <Production> to 1 in Server.xml simply turns off the development debugging framework.  So, if you want a visual indication of what didn't render properly, you'd set this new-yet-to-be-named configuration element and <Production> to 1

**Comment by mbaas2** [comment]
Ok, thanks for that clarification - that is perfectly agreeable, me thinks.
And maybe there still is room to spin off some enhancements to
error-logging which could help for production sites ;-)

2017-01-16 17:39 GMT+01:00 Brian Becker <notifications@github.com>:

**Comment by jerrymbrennan** [comment]
Brian,
Any progress in helping me get from 2 to 3 with my copy of MiServer2 I 
gave you?
Been sharing my website with schools in Thailand, Nepal, and Bhutan.
Thailand orphanage schools are particularly interested and I have 
installed some
of my older .dws based software to teach English there also.
Jerry Brennan

**Comment by bpbecker** [comment]
This was a philosophical discussion that seems to have dies out...  closing the issue
