### ISSUE TITLE
MiServer gets  closed socket when querying with cURL

### ISSUE THREAD

**Issue by JasonRivers** [Dyalog/MiServer#63]
When querying MiServer with cURL the following is posted in to the session:
```"HandleRequest" closed socket SRV00000000.CON00000000 due to error: 1001  ERR_LENGTH    sending response```

Our CI checks that the page works using curl before publishing anything, and this is causing the builds to fail.

To Reproduce (on linux):

- Run MiServer ( ```MiServer=${PWD}/MS3 dyalog ./miserver.dws``` )
- Run: curl http://localhost:8080

This ONLY applies to the development branch. master works fine.

**Comment by bpbecker** [comment]
This was interesting... because the page displays properly in a browser.  It turns out that this is because the home page for the MS3 site is large enough that it gets compressed, but the curl doesn't doesn't specify that it can accept compressed responses, so MiServer serves raw.  There are ⎕DR 160 characters in the response and this causes Conga to fail.  Converting the response with ⎕UCS fixed the problem.
