### ISSUE TITLE
How to Debug MiServer Crash?

### ISSUE THREAD

**Issue by arcfide** [Dyalog/MiServer#69]
I'm finding that my MiServer instance is going down roughly once a day. I'm trying to figure out what is the cause, but I'm not seeing a DrA file, though I think it might be generating an aplcore (testing again to be sure). The only thing anomalous in the Logs is a few entries that have "n" as their PeerAddr value, rather than the normal IPv6 address and port. 

Is there a known standard way to debug this issue? I presume that if there were a crash or the like, that this should have been logged in the DrA system if I'm running in production mode with error trapping on?

**Comment by bpbecker** [comment]
If there's an aplcore, there won't necessarily be a DrA log.  There are a few things that can be done to try to diagnose what's going on:

- You could change LogMessageLevel in /Config/Server.xml to log more activity to the session
- You could also create a derived MiServer (based on the MiServer class) and override the Log function to write that activity to a file rather than or in  addition to the session.  You'll need to set ClassName in /Config/Server.xml to the name of your derived class.
- Also if you create a derived server, there are a number of overridable entry points where you could inject additional monitoring.
